package BankModule;


/**
* BankModule/CustomerBank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Tuesday, October 24, 2017 12:13:01 o'clock AM EDT
*/

public interface CustomerBank extends CustomerBankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CustomerBank
