package BankModule;

/**
* BankModule/ManagerBankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Tuesday, October 24, 2017 12:13:01 o'clock AM EDT
*/

public final class ManagerBankHolder implements org.omg.CORBA.portable.Streamable
{
  public BankModule.ManagerBank value = null;

  public ManagerBankHolder ()
  {
  }

  public ManagerBankHolder (BankModule.ManagerBank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankModule.ManagerBankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankModule.ManagerBankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankModule.ManagerBankHelper.type ();
  }

}
