package BankModule;

/**
* BankModule/CustomerBankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Tuesday, October 24, 2017 12:13:01 o'clock AM EDT
*/

public final class CustomerBankHolder implements org.omg.CORBA.portable.Streamable
{
  public BankModule.CustomerBank value = null;

  public CustomerBankHolder ()
  {
  }

  public CustomerBankHolder (BankModule.CustomerBank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankModule.CustomerBankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankModule.CustomerBankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankModule.CustomerBankHelper.type ();
  }

}
