package BankModule;


/**
* BankModule/CustomerBankPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Tuesday, October 24, 2017 12:13:01 o'clock AM EDT
*/

public abstract class CustomerBankPOA extends org.omg.PortableServer.Servant
 implements BankModule.CustomerBankOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("deposit", new java.lang.Integer (0));
    _methods.put ("withdraw", new java.lang.Integer (1));
    _methods.put ("getBalance", new java.lang.Integer (2));
    _methods.put ("transferFund", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankModule/CustomerBank/deposit
       {
         String customerID = in.read_string ();
         double amt = in.read_double ();
         String $result = null;
         $result = this.deposit (customerID, amt);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // BankModule/CustomerBank/withdraw
       {
         String customerID = in.read_string ();
         double amt = in.read_double ();
         String $result = null;
         $result = this.withdraw (customerID, amt);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // BankModule/CustomerBank/getBalance
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBalance (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // BankModule/CustomerBank/transferFund
       {
         String sourceCustomerID = in.read_string ();
         double amount = in.read_double ();
         String destinationCustomerID = in.read_string ();
         String $result = null;
         $result = this.transferFund (sourceCustomerID, amount, destinationCustomerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankModule/CustomerBank:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CustomerBank _this() 
  {
    return CustomerBankHelper.narrow(
    super._this_object());
  }

  public CustomerBank _this(org.omg.CORBA.ORB orb) 
  {
    return CustomerBankHelper.narrow(
    super._this_object(orb));
  }


} // class CustomerBankPOA
